all:
  children:
    web_server:
      hosts:
        23.251.152.131
      vars:
        ansible_connection: 'ssh'
        ansible_user: 'ubuntu'
        ansible_ssh_private_key_file: './credentials/.credentials/ssh_key'
 